### ISSUE TITLE
the content of a dynamic table could be influenced by other note if you open multiple notes in split view  

### ISSUE THREAD

**Issue by Ravenclawer** [Aidurber/obsidian-plugin-dynamic-toc#6] opened 2021-09-06 08:02 UTC
When you create a dynamic table of content in a note and switch to another note in the split pane to create another dynamic table, the content of the previous dynamic table in the note you create before will be changed and have the content of the second dynamic table. 
the picture below would be self-explanatory.
![image](https://user-images.githubusercontent.com/73892411/132181941-bed68049-9c45-4478-ae83-055021bf2249.png)

**Comment by Aidurber** [comment] 2021-09-06 12:52
Thanks for raising this. The architecture of this plugin needs work, and is not officially released yet. I've been hacking away at it but I'm a little stuck on an issue, I've just asked the reviewer for some guidance for my last hurdle (re-rendering after settings have been saved). 

You can see the PR/code review to add it as an official release here: https://github.com/obsidianmd/obsidian-releases/pull/449

**Comment by Aidurber** [comment] 2021-09-09 10:38
Now that I understand this issue it's a duplicate of #4 Closing this in favour of that.

**Closed by Aidurber** 2021-09-09 10:38 UTC
Labels: bug
