### ISSUE TITLE
Need to switch away from active note then back, to activate the TOC

### ISSUE THREAD

**Issue by korm** [Aidurber/obsidian-plugin-dynamic-toc#8] opened 2021-09-24 11:41 UTC
Thank you for this plugin!! Exactly what Obsidian needs.

I notice that if I insert the code block then I have to switch away the focus from the active note then back to it in order to make the table of contents appear.

**Comment by Aidurber** [comment] 2021-09-24 13:33
Hi @korm I'm glad you like it! I like it too, I use it constantly 😁 

Yes I've noticed this too but could never track it down. I'll take a deep dive tomorrow.

**Comment by riuson** [comment] 2021-09-24 16:02
![Untitled Project](https://user-images.githubusercontent.com/415202/134706029-77979111-a07d-47fe-b962-9b07be86a3da.gif)

**Comment by Aidurber** [comment] 2021-09-25 10:00
Thanks for the demo @korm!

I broke down your gif into steps: 
1. Add a header
2. Switch to preview
3. Switch back to edit
4. Split the note (in edit mode)
5. Add another heading
6. On the split window change to preview
7. Add another heading. ToC doesnt update

I still couldn't reproduce the issue. 
- Can you still reproduce this on version 0.0.14?
- Can you screenshot your settings, please?

Also, the codeblock you have there is incorrect, that's including the available properties and their values (that's just for documentation purposes)

It should be: 
```markdown
```toc
style: bullet
min_depth: 2
max_depth: 6
```
```

**Comment by korm** [comment] 2021-09-25 11:07
It was @riuson who posted the GIFs.

**Comment by Aidurber** [comment] 2021-09-25 12:14
Oops 😅

**Comment by Aidurber** [comment] 2021-10-04 12:53
Closing, I can't reproduce it. Please comment with reproduction steps and I'll re-open.

**Closed by Aidurber** 2021-10-04 12:53 UTC
Labels: bug
